In [1]:
import numpy as np

## NN Interpolation

In [4]:
arr = np.array([10, 4, 22, 2, 18, 7, 9, 14, 25]).reshape((3,3))
print(arr)
print(arr.shape)
dest_size = (6, 6)

[[10  4 22]
 [ 2 18  7]
 [ 9 14 25]]
(3, 3)


In [5]:
ratio = np.array(arr.shape)/np.array(dest_size)
print(ratio)

[0.5 0.5]


In [24]:
new_row_idx = (np.ceil(np.arange(1, 1 + dest_size[0]) * ratio[0]) - 1).astype(int)
new_column_idx = (np.ceil(np.arange(1, 1 + dest_size[1]) * ratio[1]) - 1).astype(int)

print(new_row_idx)
print(new_column_idx)

[0 0 1 1 2 2]
[0 0 1 1 2 2]


In [14]:
ans = arr[:, new_column_idx][new_row_idx, :]
print(ans)

IndexError: index 3 is out of bounds for axis 1 with size 3

In [19]:
cv_img = arr
dst_h = 6
dst_w = 6

In [35]:
src_H, src_W = cv_img.shape
old_size =  cv_img.shape
row_ratio, col_ratio = np.array([dst_h, dst_w])/np.array(old_size)

print(row_ratio, col_ratio)
# row wise interpolation 
row_idx = (np.ceil(range(1, 1 + int(src_H*row_ratio))/row_ratio) - 1).astype(int)
print(row_idx)
# column wise interpolation
col_idx = (np.ceil(range(1, 1 + int(src_W*col_ratio))/col_ratio) - 1).astype(int)
print(col_idx)

print(cv_img[:, col_idx])
print(cv_img[row_idx, :])

final_matrix = cv_img[:, col_idx][row_idx, :]
print(final_matrix)
print(final_matrix.shape)

2.0 2.0
[0 0 1 1 2 2]
[0 0 1 1 2 2]
[[10 10  4  4 22 22]
 [ 2  2 18 18  7  7]
 [ 9  9 14 14 25 25]]
[[10  4 22]
 [10  4 22]
 [ 2 18  7]
 [ 2 18  7]
 [ 9 14 25]
 [ 9 14 25]]
[[10 10  4  4 22 22]
 [10 10  4  4 22 22]
 [ 2  2 18 18  7  7]
 [ 2  2 18 18  7  7]
 [ 9  9 14 14 25 25]
 [ 9  9 14 14 25 25]]
(6, 6)
